### ISSUE TITLE
not generated CIPHERSWEET_KEY in .env

### ISSUE THREAD

**Issue by fadedshadowx** [bjornvoesten/laravel-ciphersweet#10]
```
php artisan ciphersweet:key
Application key set successfully.
```

but I .env file no any new line, only edit time of file was changed.

**Comment by bjornvoesten** [comment]
Try adding the `CIPHERSWEET_KEY=` to the `.env` file and re-run the command.

**Comment by fadedshadowx** [comment]
it's helped
