### ISSUE TITLE
email rfc

### ISSUE THREAD

**Issue by fadedshadowx** [bjornvoesten/laravel-ciphersweet#11]
I'm trying to use cipher sweet with User->email and have this trouble:
```
Swift_RfcComplianceException
Address in mailbox given [nacl:zbPkZ9oTGeTiZcnlMi1NQ0D58NmRSHWRHPB0D7bFytkTH6Sva6sknj67pBiN4JDhoDI9JD3yfyYrtXG-FicP3A==] does not comply with RFC 2822, 3.6.2. 
```

**Comment by bjornvoesten** [comment]
Try decrypting the value using the `decrypt` method before accessing the email attribute.

**Comment by fadedshadowx** [comment]
If I used protected $encrypted in model, it should be automatically done I think?
When display in blade, it's ok. This error was from register page after submit form from verify function.
