### ISSUE TITLE
Decrypting with accessor in model 

### ISSUE THREAD

**Issue by fadedshadowx** [bjornvoesten/laravel-ciphersweet#12]
How to decrypt with [getEmailAttribute](https://laravel.com/docs/7.x/eloquent-mutators#defining-an-accessor)?

In model:

```
public function getEmailAttribute()
    {
        return $this->decrypt(['*'])->email;
    }
```
error: 
Undefined property: Client::$email

**Comment by bjornvoesten** [comment]
You could try something like this.
```
public function getEmailAttribute()
{
    $this->decrypt(['email']);
    return $this->attributes['email'];
}
```

One problem you have in your piece of code is that you call the email property which calls the accessor method inside the email accessor method, so that causes a loop.

**Comment by sebastiansson** [comment]
@bjornvoesten The example above does not work. Just gives:
```ErrorException Undefined property: App\Models\ModelName::$email```

![image](https://user-images.githubusercontent.com/3044878/96550627-62bd0c00-12b1-11eb-96fc-b3a939bb7c2e.png)

Have you actually tested it in the context of an [Accesor](https://laravel.com/docs/8.x/eloquent-mutators#defining-an-accessor)?

**Comment by bjornvoesten** [comment]
No I haven't tested it in the accessor context, and now that I look at it I see that it will not work because of the `$model->{$column}` that causes a loop.
