### ISSUE TITLE
Decrypt

### ISSUE THREAD

**Issue by Hesesses** [bjornvoesten/laravel-ciphersweet#5]
Hello,

Would be nice to see en example how to decrypt a field.

For example i have social_security_number field on database encrypted, how I can see the decrypted value of it?

**Comment by bjornvoesten** [comment]
That would indeed be a good addition to the documentations. 

Attributes can be decrypted by executing:
`$model->decrypt();`
or 
`$model->decrypt(['ssn']);`

This should decrypt the attributes on a model, which then can be retrieved as:
`$ssn = $model->ssn;`

**Comment by windchime18** [comment]
How to use this on laravel? to decrypt the data? It keeps saying invalid payload. I was able to successfully encrypt the data.
