### ISSUE TITLE
Decrypt is not working

### ISSUE THREAD

**Issue by windchime18** [bjornvoesten/laravel-ciphersweet#8]
I am using laravel php. I was able to successfully insert the data via use of 'HasEncryption' and   protected $encrypted. But when i query the data. I doesn't decrypt the output. Please help.

**Comment by bjornvoesten** [comment]
Try decrypting the value using the `decrypt` method. This is not documented but attributes are not automatically decrypted.

**Comment by bjornvoesten** [comment]
Try decrypting the value using the `decrypt` method. This is not documented but attributes are not automatically decrypted.
