### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by fadedshadowx** [bjornvoesten/laravel-ciphersweet#9]
I am using Laravel 7 and after composer run have error:
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for bjornvoesten/laravel-ciphersweet ^0.1.3 -> satisfiable by bjornvoesten/laravel-ciphersweet[0.1.3].
    - Conclusion: remove laravel/framework v7.28.3
    - Conclusion: don't install laravel/framework v7.28.3
    - bjornvoesten/laravel-ciphersweet 0.1.3 requires illuminate/database ^6.0 -> satisfiable by illuminate/database[6.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.18.1, v6.18.10, v6.18.11, v6.18.12, v6.18.13, v6.18.14, v6.18.15, v6.18.16, v6.18.17, v6.18.18, v6.18.19, v6.18.2, v6.18.20, v6.18.21, v6.18.22, v6.18.23, v6.18.24, v6.18.25, v6.18.26, v6.18.27, v6.18.28, v6.18.29, v6.18.3, v6.18.30, v6.18.31, v6.18.32, v6.18.33, v6.18.34, v6.18.35, v6.18.36, v6.18.37, v6.18.38, v6.18.39, v6.18.4, v6.18.40, v6.18.41, v6.18.5, v6.18.6, v6.18.7, v6.18.8, v6.18.9, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0].
    - don't install illuminate/database 6.x-dev|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.0.0|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.0.1|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.0.2|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.0.3|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.0.4|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.1.0|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.10.0|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.11.0|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.12.0|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.13.0|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.13.1|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.14.0|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.15.0|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.15.1|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.16.0|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.17.0|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.17.1|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.18.0|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.18.1|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.18.10|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.18.11|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.18.12|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.18.13|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.18.14|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.18.15|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.18.16|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.18.17|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.18.18|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.18.19|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.18.2|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.18.20|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.18.21|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.18.22|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.18.23|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.18.24|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.18.25|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.18.26|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.18.27|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.18.28|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.18.29|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.18.3|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.18.30|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.18.31|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.18.32|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.18.33|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.18.34|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.18.35|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.18.36|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.18.37|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.18.38|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.18.39|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.18.4|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.18.40|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.18.41|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.18.5|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.18.6|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.18.7|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.18.8|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.18.9|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.2.0|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.3.0|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.4.1|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.5.0|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.5.1|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.5.2|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.6.0|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.6.1|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.6.2|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.7.0|don't install laravel/framework v7.28.3
    - don't install illuminate/database v6.8.0|don't install laravel/framework v7.28.3
    - Installation request for laravel/framework (locked at v7.28.3, required as ^7.28) -> satisfiable by laravel/framework[v7.28.3].

How to fix this?

**Comment by bjornvoesten** [comment]
I have not tagged the latest updates which update the Laravel compatibility, you may try using the master branch as the version.
